apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diun
  namespace: argocd
  labels:
    name: diun
  # remove this for prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sinicide/sh-repo
    targetRevision: HEAD
    path: yamls/diun

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3

