apiVersion: v1
kind: Service
metadata:
  name: koillection-postgres-db
  namespace: databases
spec:
  selector:
    app: koillection-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      name: db