apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koillection-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 5Gi