apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi