apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
data:
  PAPERLESS_REDIS: "redis://paperless-redis-db.databases:6379"
  PAPERLESS_URL: "https://paperless-temp.sin.lan"
  # Tika
  PAPERLESS_TIKA_ENABLED: "true"
  PAPERLESS_TIKA_ENDPOINT: "http://paperless-tika:9998"
  # 
  PAPERLESS_CONSUMPTION_DIR: "/tmp/consume"
  PAPERLESS_BASE_DIR: "/paperless"
  PAPERLESS_DATA_DIR: "/paperless/data"
  PAPERLESS_TRASH_DIR: "/paperless/trash"
  PAPERLESS_MEDIA_ROOT: "/paperless/media"
  PAPERLESS_STATICDIR: "/paperless/static"
  PAPERLESS_LOGGING_DIR: "/tmp/log"
