kind: Deployment
apiVersion: apps/v1
metadata:
  name: paperless-redis-db
  namespace: databases
  labels:
    app: paperless-redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-redis-db
  template:
    metadata:
      labels:
        app: paperless-redis-db
    spec:
      containers:
        - name: paperless-redis-db
          image: redis:7.0.11
          ports:
            - name: db
              containerPort: 6379
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          volumeMounts:
          - name: paperless-redis-db-pv
            mountPath: "/data"
      volumes:
        - name: paperless-redis-db-pv
          persistentVolumeClaim:
            claimName: paperless-redis-db-claim