apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-redis-db-claim
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 2Gi